add_test([=[PrinterTest.Initialization]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=PrinterTest.Initialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PrinterTest.Initialization]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PrinterTest.MoveSemantics]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=PrinterTest.MoveSemantics]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PrinterTest.MoveSemantics]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PrinterTest.DefaultInitialization]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=PrinterTest.DefaultInitialization]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PrinterTest.DefaultInitialization]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[PPDValueTest.StringSafety]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=PPDValueTest.StringSafety]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[PPDValueTest.StringSafety]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SemaphoreTest.BasicAcquireRelease]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=SemaphoreTest.BasicAcquireRelease]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SemaphoreTest.BasicAcquireRelease]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SemaphoreTest.MultiRelease]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=SemaphoreTest.MultiRelease]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SemaphoreTest.MultiRelease]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SemaphoreTest.ThreadSync]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=SemaphoreTest.ThreadSync]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SemaphoreTest.ThreadSync]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Algo0x11Test.CompressionCorrectness]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=Algo0x11Test.CompressionCorrectness]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Algo0x11Test.CompressionCorrectness]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Algo0x11Test.EmptyInput]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=Algo0x11Test.EmptyInput]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Algo0x11Test.EmptyInput]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Algo0x11Test.LargeEmptyBuffer]=]  /workspace/build_ppd_local/splix_gtest [==[--gtest_filter=Algo0x11Test.LargeEmptyBuffer]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Algo0x11Test.LargeEmptyBuffer]=]  PROPERTIES WORKING_DIRECTORY /workspace/build_ppd_local SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  splix_gtest_TESTS PrinterTest.Initialization PrinterTest.MoveSemantics PrinterTest.DefaultInitialization PPDValueTest.StringSafety SemaphoreTest.BasicAcquireRelease SemaphoreTest.MultiRelease SemaphoreTest.ThreadSync Algo0x11Test.CompressionCorrectness Algo0x11Test.EmptyInput Algo0x11Test.LargeEmptyBuffer)
