function(splix_debian_architecture output processor)
    string(TOLOWER "${processor}" normalized_processor)
    if(normalized_processor MATCHES "^(x86_64|amd64)$")
        set(debian_arch "amd64")
    elseif(normalized_processor MATCHES "^(aarch64|arm64)$")
        set(debian_arch "arm64")
    elseif(normalized_processor MATCHES "^(armv7|armv7l|armhf)$")
        set(debian_arch "armhf")
    elseif(normalized_processor MATCHES "^(i[3-6]86|x86)$")
        set(debian_arch "i386")
    elseif(normalized_processor STREQUAL "riscv64")
        set(debian_arch "riscv64")
    else()
        message(FATAL_ERROR
            "Unsupported Debian package processor: ${processor}")
    endif()
    set(${output} "${debian_arch}" PARENT_SCOPE)
endfunction()
